#!/bin/python3

import math
import os
import random
import re
import sys
import string

def solve(s):
    lst = []
    name = ""
    lst = s.split(" ")
    print(lst)
    for i in range(len(lst)):
        lst[i] = lst[i].capitalize()
    for j in range(len(lst)):
        if j == 0:
            name = lst[j]
        else:
            name = name +" "+lst[j]
    return name

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    s = input()

    result = solve(s)

    fptr.write(result + '\n')

    fptr.close()
